---
title: "CDOC project"
output:
  github_document:
    html_preview: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(feather)

literature_dataset <- read_feather("dataset/clean/literature_datasets.feather")
cdom_dataset <- read_feather("dataset/clean/cdom_dataset.feather")
```

## Motivations

Numerous studies are presenting graphics or data about the DOC/aCDOM relationship. However, there are at least two potential problems:

1. Given that results are often study-specific, we are clearly missing the big picture since the results are rarely discussed from a broader perspective.

2. People are using different wavelengths (254, 300, 350, 400, …) to present aCDOM data, hence preventing literature comparisons.

The idea of this project is to use published data to explore the relationships between DOC and aCDOM across a large gradient of ecosystems (from lakes to open ocean) in order to highlight potential drivers influencing such relationships. Additionally, we could use this opportunity to:

* Provide a “standard” value for the wavelength used to report aCDOM.

* Find patterns or drivers in CDOM/DOC relationship.

* Provide/advertise an open aCDOM repository (database) where researchers could deposit their published data. Given that aCDOM is nowadays routinely measured in most ecological studies, this could provide a central point for further research on aCDOM.

## Published article

This work has been published in [STOTEN](https://www.journals.elsevier.com/science-of-the-total-environment/) and should be cited as:

Massicotte, P., Asmala, E., Stedmon, C., & Markager, S. (2017). Global distribution of dissolved organic matter along the aquatic continuum: Across rivers, lakes and oceans. Science of The Total Environment, 609(C), 180–191. https://doi.org/10.1016/j.scitotenv.2017.07.076